media-suite_compile.sh
Missing libs:
- openjpeg
- libgnurx
- libmad
First compilation from master but never get updates:
- xavs (doesn't get many updates anyway)
- mediainfo
- decklink
The rest all get compiled from vcs so they always get updated when needed.
=> Change most versioned libs to use pkg-config instead of just checking if lib exists

.gitattributes, media-suite_compile.sh
Also fix problems with LF endings in the .bat file.
And add "noDepth" to luajit.
=> Fix GnuTLS compilation since MinGW updated Nettle.

media-suite_compile.sh
We'll wait for gpac to reply before commiting this.
=> Build gpac and mp4box shared

media-autobuild_suite.bat, media-suite_compile.sh
Should be fine to merge as is since it uses the same options by default, but since it will be a big change overall I'll keep this as a PR until I've made every lib optional and until I find a way to notify of the possibility of using your own `ffmpeg_options.txt` file.
=> Improved FFmpeg options

media-autobuild_suite.bat, media-suite_compile.sh
=> Allow both shared and static FFmpeg

build/media-suite_compile.sh
FreeType: updated to 2.8.1 to adapt fontconfig
=>  FreeType: updated to 2.8.1 to adapt fontconfig

build/media-suite_compile.sh
=> fribidi: use a mirror

build/media-suite_compile.sh
Using changes to the code proposed in the discussion for issue #630, this will fix gnutls (for now at least), stop MABS from hanging, and would allow #630 to be closed.
=> Fix gnutls

media-autobuild_suite.bat
It will allow to launch compilation with environment variables for the VC compiler which are set by vcvarsall.bat script.
=> Better compatibility with the VC compiler

build/media-suite_compile.sh
=> vulkan: remove vulkan/vk_layer_dispatch_table.h from _check()

build/media-suite_compile.sh
Fixes https://github.com/jb-alvarado/media-autobuild_suite/issues/868
=> apache-ant: use remote version

build/media-suite_compile.sh
=> vpx: disable avx512

build/media-suite_update.sh
Use pacman-key instead of grep to confirm existence of abrepo key and also confirm if the key is locally signed, else sign.
idk if this is actually how to do a pull request.
=> Use pacman-key instead of grep and also fix gpg key not being signed.

build/media-suite_update.sh
Make it so that pacman-key doesn't output anything to console if the key exists.
=> Update.sh : added >/dev/null for the pacman-key check

doc/forcing-recompilations.md
Added in some of the new exe created to the forcing-recompilation.md page.
=> Recompilation.md: Added dssim, jq, rg, davs2, xavs2, ffmsindex, rav1e, dav1d, and vvc

doc/getting-started.md
Created getting-started.md to point people to if they ask ask what to do with the files after compiling.
#999
=> Getting-Started.md: Added a getting-started doc.

build/media-suite_compile.sh
Fixes https://github.com/jb-alvarado/media-autobuild_suite/issues/1035
=> libzmq: fix sed

build/media-suite_compile.sh, media-autobuild_suite.bat
should fix https://github.com/jb-alvarado/media-autobuild_suite/issues/1044
=> avs2: build binaries if standalone=y

media-autobuild_suite.bat
Added preliminary check if powershell version if less than 4.
=> Batch: Error if powershell version is less than 4

media-autobuild_suite.bat
Replaced wget-pack.exe functions with powershell equivalent. https://github.com/jb-alvarado/media-autobuild_suite/pull/1041
It tested working for me.
=> Batch: Removed wget-pack.exe, replaced functions with powershell

media-autobuild_suite.bat
I realized that I was still using mintty, and not just bash.
=> Batch: Fixed minttyrc not being written to

build/media-suite_compile.sh, build/media-suite_helper.sh, media-autobuild_suite.bat
Added timestamps in the form of `HH:MM:SS $*`. Also bolded the ├ to match the ┌ and └.
=> Helper: Added timestamps to console output

README.md, build/media-suite_compile.sh
Ideally, you shouldn't need enter any text here, and your commit messages should
explain your changes sufficiently (especially why they are needed).
=> Opus & shaderc

media-autobuild_suite.bat
Formatted parenthesis to end on the same column as they had begun.
Formatted indentions to match correct indentations.
Removed unnecessary inventions.
Tried to make lines around 80-90 characters long.
I need to find out how to properly break quoted strings
=> Batch: Formatting for consistency

media-autobuild_suite.bat
Removed the unnecessary write{iniOptions} variable
shortened the deleteINI to echo.{iniOptions}
=> Batch: Removed unnecessary write* variable

build/media-suite_helper.sh
Noticed that do_pacman_* has their own echo and didn't have timestamps.
=> Helper: Added timestamps to do_pacman_*

build/media-suite_compile.sh
https://gitlab.com/gnutls/gnutls/merge_requests/905
I don't know how long until they merge that but we can use it already.
=> gnutls: use unofficial but already tested gnutls team ccr patch

build/media-suite_helper.sh
Strip anything matching ##:##:## from the beginning of the line from the log files.
=> Helper: Strip timestamps with ansi

build/media-suite_compile.sh
Should fix #1077 according to hubert
=> Compile: Use cmake with libsndfile. Fixed #1077

media-autobuild_suite.bat
We can either use pacboy or just replace the x and i with x86_64 and i386.
=> Batch: Condense getmingws into one with Pacboy

media-autobuild_suite.bat
https://github.com/jb-alvarado/media-autobuild_suite/pull/1109#issuecomment-467678419_
=> Batch: fix mistake pointed out by hubert

media-autobuild_suite.bat
https://github.com/jb-alvarado/media-autobuild_suite/commit/721cf538a0c7defcddf2c3c5f5d21ca27f9111d3#commitcomment-32500964
=> Batch: Fixed problem pointed out by Ligh-De

build/media-suite_compile.sh
Fixes https://github.com/jb-alvarado/media-autobuild_suite/issues/1104
=> libopenh264: fix checksum for download

.gitignore, README.md, build/media-suite_compile.sh, build/media-suite_helper.sh
I still need to do some clean up, but here is what I have currently.
Ping @lars18th @schmidthubert if there is anything that you guys would like to change/add
I'm not sure if this is all needed, but I went with trying to add as much as directives as possible.
=> Add Custom Patches. Closes #1163

build/media-suite_compile.sh
=> Vulkan-Headers: Use known_good.json for Vulkan-Headers

README.md, build/media-suite_helper.sh
@lars18th Please check if this is okay.
=> do_patch: Add local patches capability. Closes #1176 #1178

build/media-suite_compile.sh
Closes #1179 (?)
@Selur and @Helenerineium  , can you confirm if this fixes the error?
I think there might be a problem with jq still because of #1179 and #1172 . Will need to investigate
=> Vulkan: Use update_deps.py to get correct version of headers.

build/media-suite_helper.sh
=> do_vcs: Add gitlab fallback

build/media-suite_helper.sh
Accidentally forgot to remove extra else when I combined the ifs
Fixes #1191 and fixes #1192
=> Do_vcs: fix regression from fallback. Fixes #1191

build/media-suite_update.sh
reduces time by .01 s on each one.
=> update: remove call to cat for packages

README.md, build/media-suite_compile.sh, build/media-suite_helper.sh
=> mpv: Add extra_script hooks and add generic build hook.

README.md, build/media-suite_helper.sh
=> extra_script: Add recompile flag. Closes #1186 

build/media-suite_helper.sh
Any way to make this a little better, @1480c1 ? I think you're way more comfortable with cmake than I am.
=> Create cmake toolchain file and use it to set some sane values

media-autobuild_suite.bat
For future purposes of adding other stuff to the build folder that may need to be repopulated (json)
=> bat: add bash.ps1 to list of scripts to download to the build folder

build/media-suite_compile.sh
=> ant: update to 1.10.6

build/media-suite_compile.sh
One less do_wget we would need to worry about
=> faac: change to github from sf

media-autobuild_suite.bat
=> Bat: fix logic for wgetting script

build/media-suite_compile.sh
Fixes https://github.com/jb-alvarado/media-autobuild_suite/issues/1202
=> ffmbc: fix build

build/media-suite_compile.sh
New patch due to changes in 213
=> svthevc: new transition patch due to changes

build/media-suite_compile.sh
=> spirv-cross: use lachs0r's branch

build/media-suite_compile.sh
Forgot I had added a NATIVE flag for using march=native
=> svthevc: don't use march=native flag

build/media-suite_compile.sh, media-autobuild_suite.bat
Needs to be tested as the patches are based off the 4.1 branch
=> svthevc: add SVT-HEVC to ffmpeg

build/media-suite_compile.sh
=> svthevc: remove merged pull request patches

media-autobuild_suite.bat
*Add libsvthevc to ffmpeg_options_full - default is deactivated so that it is also written to the txt-file*
This is my first pull request, please be patient with me, I am learning and hoping to make it right. :)
=> Add libsvthevc to ffmpeg_options_full

build/media-suite_compile.sh
Add svt-hevc to x265, Closes #1103
Also try to simplify x265 building a little bit.
=> x265: add svt-hevc

build/media-suite_compile.sh
See https://code.videolan.org/videolan/dav1d/commit/beda6e0d1c37f06e4e03f7ebe13311bd8b18245e
=> dav1d: sync upstream changes

build/media-suite_compile.sh
=> OpenCL-Headers: use latest version from git

build/media-suite_compile.sh
The original commit disappears because of rebase and force-push.
=> vapoursynth_alt: switch to gist

build/media-suite_compile.sh
=> dav1d: Move up and disable dav1dplay

build/media-suite_compile.sh
=> sdl2: Update to 2.0.10

build/media-suite_helper.sh
Does echo even have an exit code other than zero?
=> Escapes: Use single quotes for some, combine two echos into printf

build/media-suite_helper.sh
add something similar to the exit prompt of cd_safe for push and popd
Split localizing variable and setting from subshell
=> Helper: Add exit prompt if pushd and popd failed

build/media-suite_helper.sh
=>  create_ab_pkgconfig: Remove declare function and unix2dos

build/media-suite_helper.sh
=> compare_with_zeranoe: Split local and set, remove dos2unix

README.md, build/media-suite_compile.sh, media-autobuild_suite.bat
Add openal to ffmpeg_options_full and mpv_options_full
=> Add openal

build/media-suite_compile.sh
=> openal: Fix building

README.md
=> Readme: add powershell with link to requirements

build/media-suite_compile.sh
=> do_simple_print: Add wrapper for timeStamp for printing messages

build/media-suite_compile.sh, build/media-suite_helper.sh, media-autobuild_suite.bat
=> SVT-HEVC: Remove shared libs

build/media-suite_helper.sh, build/media-suite_update.sh
Rework to accept msys2 packages and remove extra calls to grep
=> do_pacman: Rework do_pacman_* to accept msys2 packages

build/media-suite_compile.sh, media-autobuild_suite.bat
SVT-AV1 seems to work fine.
Don't merge until SVT-AV1 properly gets mingw support
https://github.com/jb-alvarado/media-autobuild_suite/issues/1094
=> Compile: Add SVT-AV1

build/media-suite_helper.sh
going to test to make none of this is breaking
=> Helper: Run shfmt

build/media-suite_compile.sh, build/media-suite_helper.sh, media-autobuild_suite.bat
Add sccache (ccache but for rustc etc)
Combine jq checks since they both check for jq.
Technically speaking, we could try to replace ccache with sccache, problem is that we can't disable sccache like ccache.
=> rust: add sccache

build/media-suite_compile.sh
See https://github.com/KhronosGroup/Vulkan-Loader/commit/524c70c669c0d84663977f7d74fbd77d2f07936f and https://github.com/DeadSix27/python_cross_compile_script/commit/f365d484f948e2cbcafcce52b0cec030348f8e50
=> vulkan: remove dxgi workaround

build/media-suite_helper.sh
Add nocd and print option accessible using `create_build_dir -c` and `-p` options in order to be able to create a directory without necessarily cding into it and print a full path to pass to other tools (meson and cmake)
=> create_build_dir: Add nocd and print options

README.md, build/media-suite_compile.sh, media-autobuild_suite.bat
Add xvc: https://github.com/divideon/xvc
https://xvc.io
Claims to be a HEVC and AV1 competitor in terms of performance.
Seems to be interesting enough, however, since it doesn't have an ffmpeg plugin or others, I feel that it may be limited in use.
Related doom9: https://forum.doom9.org/showthread.php?t=175110
=> xvc: Add xvc

build/media-suite_compile.sh
Removed SVT-AV1 MinGW patch since it has been merged into SVT-AV1
=> Remove merged SVT-AV1 MinGW patch

build/media-suite_compile.sh, build/media-suite_helper.sh
=> do_rust: Unset RUSTC_WRAPPER if command -v sccache fails

build/media-suite_helper.sh, media-autobuild_suite.bat
Contains improvements for noMintty through use script.exe, now doesn't require the hackish bash.ps1
Includes some style changes towards using `::` as comments and replace them with proper `rem` comments since technically speaking `::` is not actually a comment but a label with `:` as the name
Tested with noMintty=1 and =0
=> Batch: Improve a couple things

media-autobuild_suite.bat
Fix an oversight in https://github.com/m-ab-s/media-autobuild_suite/commit/077ff18597c5ba8195dc151b097a5722e3d4f4ec
=> Fix an oversight

build/media-suite_compile.sh, media-autobuild_suite.bat
Closes #1094
I haven't added the ffmpeg plugin since there already seems to be some issues with svt-{av1,hevc} ffmpeg etc
=> SVT-VP9: Add SVT-VP9

build/media-suite_compile.sh
Temp fix for #1441 to apply the pr while it's open and mergeable since it seems it may take some time for upstream to merge
=> SVT-AV1: Apply 717 patch if pr is still open and mergeable

media-autobuild_suite.bat
=> bat: add jo to compileArgs

build/media-suite_helper.sh
=> helper: also print CPPFLAGS and CXXFLAGS in log

build/media-suite_compile.sh
=> faac: update to 1_30

README.md, build/media-suite_compile.sh
and update README with recent changes
=> Update vapoursynth to R48

build/media-suite_helper.sh
`pacman -Qqe` does not actually accept regex it seems, `pacman -Qqs` does accept regex though.
=> do_pacman*: Fix actually skipping if not applicable

build/media-suite_helper.sh
Because of batch dumb processing, '=' are stripped.
Closes #1468
I had to revert the other one since it was causing issues even though I tested it.
=> create_ab_ccache: Use cygpath. Don't try to preprocess args

media-autobuild_suite.bat
Fixes #1458
@wiiaboo, should I start doing my development on the main repository or just keep using my personal fork? It's starting to get a bit annoying trying to remember which repo I'm pushing to (m-ab-s, personal, gitlab m-ab-s, and personal m-ab-s)
=> bat: Use 7za from chocolatey

media-autobuild_suite.bat
Workaround for the problems in #1483
=> Temporarily disable librav1e

build/media-suite_helper.sh
Planning to use this in another changeset for `do_vcs` to actually use a fallback url
=> log: Add option to not use compilation_fail

build/media-suite_helper.sh
Adds:
- `vcs_get_default_ref`
- `vcs_get_current_type`
- `vcs_get_current_head`
- `vcs_test_remote`
- and an internal `do_mabs_clone`
Probably best to review commit by commit
=> do_vcs: Rework to use a lot more case switches

build/media-suite_compile.sh
Tested and everything compiled fine
=> aom: Add vmaf tune support

build/media-suite_helper.sh
Haven't fully tested if there's any speed improvements, will try too
=> do_vcs: Some more cleanup and improvements(?)

build/media-suite_compile.sh
=> x265: Changed x265 hg source to x265 git.

build/media-suite_compile.sh, build/media-suite_helper.sh, media-autobuild_suite.bat
It seems sccache is causing a lot of annoyance and there doesn't seem to be anything to fix them right now and I don't think it's worth the hassle and effort for now
Closes #1554
Closes #1403
=> sccache: Remove sccache

build/media-suite_compile.sh
=> vlc: Move prefix to local##/vlc

build/media-suite_compile.sh
Increased version number and updated hash.
Fixes #1589
=> Push Xvid to v1.3.7

build/media-suite_compile.sh
Update Python to 3.8.2 and Vapoursynth to R49
=> Update Python and Vapoursynth

build/media-suite_compile.sh, media-autobuild_suite.bat
=> Added Exhale xHE-AAC encoder

README.md, build/media-suite_compile.sh
Adds exhale to the "other tools" section.
=> README: Add exhale

build/media-suite_compile.sh
Changed exhale do_make with do_cmakeinstall
=> exhale: do_cmakeinstall

build/media-suite_compile.sh
=> compile.sh: fix missing "="

build/media-suite_compile.sh
=> Fix bitness comparison for vvc

media-autobuild_suite.bat
Might help with people who want to compile in the background, we could add more priority options too
=> Bat: Add low prio option

build/media-suite_compile.sh
Closes #1678
Only done manual compilation tests, haven't actually ran it through the full suite yet
=> luajit: Install luajit from git

media-autobuild_suite.bat
Not too sure about adding libvmaf as it needs w32threads disabled.
Any opinion on this?
=> .bat: update with newer zeranoe included libs

build/media-suite_compile.sh
=> Bump VapourSynth release to 52

build/media-suite_compile.sh
github is archived, only gitlab is used
you know... 😉😜
=> update SVT-AV1 repo URL

build/media-suite_compile.sh
fixes m-ab-s/media-autobuild_suite#2100
=> jpeg-xl: fix cmake configuration

build/media-suite_compile.sh, media-autobuild_suite.bat
=> Build FFmpeg with libplacebo

build/media-suite_compile.sh
Fixes #2126 
I don't fully understand about understand media-suite_helper.sh ,so there may be a better way
=> ffmpeg need  avisynth version.h

build/media-suite_compile.sh
The last changes by @okazunori2013 are not correct. Process failed.
=> fix avisynth build process

doc/getting-started.md
Issue #1021 fixed in PowerShell/PowerShell#11057, released in v7.0.0-preview.6, so available from version 7.0.0
Last Powershell version is 5.1 so 6 was already Powershell Core
=> getting-started: Issue fixed

build/media-suite_compile.sh
libjxl now compiles after libwebp and before OpenCL
My reasoning for moving it is that it may be useful in the future to enable compiling libaom-av1 with butteraugli enabled, and JPEG XL isn't a video codec (it supports animation, but the primary focus is on still images) so moving it away from video tools should be appropriate
=> libjxl: remove cjxl_ng, move compilation to global tools

media-autobuild_suite.bat
HHI is the Heinrich Hertz Institute.
=> Fix company name "Fraunhofer HHI"

build/media-suite_compile.sh
remove duplicates
[mpv#2253](https://github.com/mpv-player/mpv/issues/2253) 
It seems that what was added  at #140 was but seems to have been removed at some point.　Do you know why it was removed?
Fixes #2214
=> fix mpv build

build/media-suite_compile.sh, build/media-suite_helper.sh
Implements https://github.com/m-ab-s/media-autobuild_suite/issues/2367
=> Allow specific versions for shaderc dependencies

build/media-suite_compile.sh
Fixes https://github.com/m-ab-s/media-autobuild_suite/issues/2463
=> highway: Disable building tests

build/media-suite_compile.sh
Here's the do_patch one-liner for the new luajit patch, as we talked about earlier.
=> Add do_patch for new luajit rolling release patch (0005)

build/media-suite_compile.sh
=> rust check for dovitool

build/media-suite_compile.sh
=> vapoursynth: update to R68+python3.12.3

build/media-suite_compile.sh
=> Correct path prefix for libgit2 artifacts

media-autobuild_suite.bat
Reduces the time consumed when running the suite multiple times in a short period.
=> Implement some interval for msys2 package update

build/media-suite_compile.sh
=> Update media-suite_compile.sh to support libvvdec in ffmpeg

build/media-suite_compile.sh, media-autobuild_suite.bat
=> Fix the clang pthread problem of liblc3 standalone tools and adjust some default ffmpeg options in bat

build/media-suite_compile.sh, build/media-suite_helper.sh
Rust error: `the x86_64-pc-windows-gnu target may not be installed`
=> Fix rust building for clang env, install rust for av1an, check if vvdec is enabled in ffmpeg

README.md, build/media-suite_compile.sh, media-autobuild_suite.bat
Some changes I should've caught with my original av1an commit. Should mostly address #2775
=> av1an: minor fixes

build/media-suite_compile.sh, media-autobuild_suite.bat
* Download `media-suite_deps.sh` if not found
* Update upx, gnutls, libidn2, libpsl, and openh264 to their newest versions
* Make the msys2 package update interval configurable in .ini
I set up `pkgUpdateTime` to not require user input because the default of one day is good enough, and I don't think it would be necessary to change it unless a user *needed* more frequent package updates
=> Misc improvements

build/media-suite_compile.sh
=> av1an: fix compilation

build/media-suite_compile.sh
Enabling CMake parameter changed from ON to SYSTEM
Fixes #2816
=> Re-enable codecs in libavif

build/media-suite_helper.sh
At present, the script validates any reference string against named refs only, so literal hash refs don't get checked out. FIxed.
=> Fix updating repo to a specific commit

build/media-suite_compile.sh
ffmpeg 8224327698 changed all defines of FF_PROFILES_* to AV_PROFILES_*
=> patch lavc/vvdec to unbreak ffmpeg build

build/media-suite_compile.sh, build/media-suite_deps.sh, media-autobuild_suite.bat
Currently the static link doesn't work.
Maybe better wait sometime to see if it will be fixed?
=> Add openapv (enable through FFmpeg options only) and misc change

build/media-suite_compile.sh
Partially fix https://github.com/m-ab-s/media-autobuild_suite/issues/2925
=> FIx AudioToolbox linking with ffmpeg shared

build/media-suite_helper.sh
I just added a specific new option for the logging in extra_script so nothing else should be affected this time.
=> Fixed Allow *_extra.sh scripts to print info.

build/media-suite_helper.sh
Adds the ability to not apply any patches.
=> Add way to disable patching

media-autobuild_suite.bat
This PR handles the situation reported in issue #2973.
=> Prevent infinite loop if av1an >2
