m-ab-s/media-autobuild_suite

media-autobuild_suite.bat, media-suite_compile.sh
Only tested this with my usecase (64-bit only).
Will test with 32-bit as well tomorrow.
The separate "build_successful$bits" mean that in case something happens during 64-bit compilation the 32-bit won't get compiled again.
=> Use only one build dir

media-autobuild_suite.bat, media-suite_compile.sh
You can delete the other. This one has same and more changes and it's in a separate branch.
About using the new do_wget with zip and 7z, I don't think it's worth it. You need more lines of code to support the couple of files that are not .tar.* than to keep using the old do_wget.
In the future a better and more efficient way can be used, but for now, this is good enough, IMO.
That said, I still haven't tested with 32-bit and 64-bit together, so don't merge this yet.
=> Wget improve

media-autobuild_suite.bat, media-suite_compile.sh
These are the options that should not be optional to choose since they all take a long time to build and add a bit of size to ffmpeg (vpx, x264 and x265).
People might also not want mediainfo and sox. SoxR can still be built without Sox since it's just its resampling library.
The last two commits make x264 and x265 actually optional, since we now only choose between building binaries and libs or libs only.
The rest of the options will be behind one last option, so we can merge this now and save the rest for a later bunch of commits in a week or more so we don't delete people's INIs too much.
=> Optional apps

media-suite_compile.sh, patches/ffmpeg-use-pkg-config-for-more-external-libs.patch
FFmbc can be left as is since it's based on an old version of FFmpeg, so things might or not break if we take extra-libs off, but I just finished a full compilation from scratch and there were no problems.
How about on your side, @jb-alvarado ?
=> Remove redundant extra-libs from ffmpeg

media-autobuild_suite.bat, media-suite_compile.sh
Qt version of mkvtoolnix's GUI has come out of alpha. After 8.0.0, the wxGTK version will be considered deprecated.
Problems with this:
We need either to compile qtbase (just `make clean` takes ages) for ourselves or install `qt5-static`.
Compiling by ourselves takes a buttload of time to make and clean but we get a lighter version of qt.
Installing qt5-static we add a 500MB download and 3GB install size just from that, but I've confirmed installation works with the latter.
I haven't been able to finish the compilation of Qt yet, and I don't think it's worth it.
To prevent this 3GB behemoth from getting installed even if you aren't compiling mkvtoolnix, we could add a mechanism to only install it if mkvtoolnix is selected.
=> Mkvtoolnix Qt GUI

README.md, media-autobuild_suite.bat, media-suite_compile.sh
These commits modify the compilation script to build a static kvazaar library and enable it when building FFmpeg.
=> Enable libkvazaar in FFmpeg

media-autobuild_suite.bat
Fix for msys installation script break due to syntax.
=> modified:   media-autobuild_suite.bat

build/media-suite_compile.sh
Small syntax fix for libmysofa install detection
=> libmysofa: fix install check

build/media-suite_compile.sh
x265 removed x265-extras.h in 563cbe1 so the use of sed is not relevant anymore.
=> Remove sed call for non-existent file in x265

build/media-suite_compile.sh
When the merge with mruby fails, the current code adds the option "--disable-mruby" to the MPV_OPTS.
This breaks the MPV configuration with the error : --disable-mruby unknown option.
This commit will remove the option --enable-mruby from the array MPV_OPTS
=> MPV does not accept --disable-mruby 

build/media-suite_compile.sh
To avoid aomenc failing with segmentation faults during encoding when it is built with GCC 8.2.0 (currently only in MinGW64 in the MSYS2 project), the compiler flag -fno-tree-slp-vectorize could be added for GNU C/C++ compilers. The crash is caused by the compiler producing instructions with unaligned memory access.
=> AOM with no-tree-slp-vectorize for GCC 8.2.0

build/media-suite_compile.sh
library and package config file use different file names; to be postponed until static building with glib2 is fixed
=> separate liblensfun.a from lensfun.pc in _check

build/media-suite_compile.sh
It's working again, compilation of lib went through without any further changes, ffpmeg built OK as well.
=> Revert "tesseract: clamp to older commit"

build/media-suite_compile.sh
Temporary workaround to avoid incompatibility issues with OpenSSL 1.1 – based on changes suggested by @slyfox1186 in https://github.com/jb-alvarado/media-autobuild_suite/issues/930#issuecomment-424733584
=> Disable http related opus tools features

media-autobuild_suite.bat
Python/Meson will not run/crash/segfault if PYTHONPATH from Windows is used. If Windows PYTHONPATH would be somewhere required during building it's always possible to query the Windows registry for it.
=> Ignore Windows PYTHONPATH during build

build/media-suite_update.sh
tasklist is not fit for what we want to do here. Since ps without -W argument doesn't show any Windows processes this will kill msys's gpg-agent only and not the wrong or any other gpg-agent running in the Windows session.
=> updater: don't kill the wrong gpg-agent

build/media-suite_compile.sh
The new version doesn't seem to break anything.
Here's my [compile.log](https://github.com/jb-alvarado/media-autobuild_suite/files/2599478/compile.log) if interested.
=> Update SDL2 to 2.0.9

build/media-suite_compile.sh
autobuild is renamed to autogen.sh in [b925cbc](https://github.com/DanBloomberg/leptonica/commit/b925cbcf5fe1abe5a45284ef0e3f97612ef773f2)
=> Fix leptonica

build/media-suite_compile.sh, build/media-suite_update.sh, media-autobuild_suite.bat
Change cyanrip's variables to match the others and the removal of the tabs in the white space was caused by visual studio code.
=> Cyanrip: replace yes and no with y and n, also remove extra tabs in whitespace.

media-autobuild_suite.bat
Removed unnecessary semicolon and also made sure downloadfile has an 'absolute path' along with some formatting. This will fix the problem of running the script from powershell and failing to download. (downloadfile requires an absolute path and can't handle relative if running from powershell)
=> batch: Modified wget.ps1 to match proper syntax along with some formatting.

media-autobuild_suite.bat
Since kvazaar can be built with ffmpeg, I removed the standalone word from the question since it seemed like it implied that kvazaar can only be built as a standalone exe and could not be included anywhere else.
=> batch: Removed standalone keyword from Kvazaar.

LICENSE, media-autobuild_suite.bat
Added a s to the link in the license in the batch and copy and pasted the license from [fsf](https://www.gnu.org/licenses/gpl-3.0.txt).
=> Batch & License: Updated license with https links to match GPLv3 license

build/media-suite_update.sh
We shouldn't play with that option, anyone who wants to downgrade/ignore new *crap* packages for a while like currently in the zeromq case should be able to revert to a previous working package. If necessary add the list of installed packages to the error log(s) instead if this is required for problem analysis  :+1:
=> update.sh: (re-)enable IgnorePkg option in /etc/pacman.conf

media-autobuild_suite.bat
Based on warnings from <https://www.robvanderwoude.com/battech_batcodecheck.php> and <https://ss64.com/nt/errorlevel.html>. Using if errorlevel 0 checks for any errorlevel greater than or equal to 0 (including if the command gave an errorlevel of 1), instead of if the previous command did not error.
=> Batch: Modified logic for checking INI due to how errorlevel works

media-autobuild_suite.bat
There was a missing ^ for the parenthesis in the path is greater than 60 characters warning.
=> Batch: Added a carrot for unescaped parenthesis

build/media-suite_update.sh
Should fix the problem mentioned by @schmidthubert in https://github.com/jb-alvarado/media-autobuild_suite/pull/1042 with pacman asking if the key should be imported.
Added another >/dev/null for the pacman-key.
=> Update.sh: Added autoyes if pacman can't find abrepo key. 

media-autobuild_suite.bat
Properly made it so that it will try to download msys2 5 times and if the download errors out and exit straight to the error message so it doesn't download PSCX etcetera it after the fifth time.
=> Batch: Fixed the retry loop for downloading msys2

media-autobuild_suite.bat
Will compare the file size of the tar.xz and if it doesn't match the size reported by the header from the repo, it will download, exiting with 1 if it fails 5 times. If the file doesn't exist, it will still not equal the size reported by the header.
=> Batch: Download msys2 if it doesn't match the header from repo

media-autobuild_suite.bat
Idk if this is necessary. Felt weird because it keeps on setting a local environment everytime write Option is called in the options file without ending the local environment part.
=> Batch: Changed one of the setlocal in writeOption to endlocal

media-autobuild_suite.bat
Add a note about Windows 10 Defender's real-time protection spending ~50-60% of cpu power to scan the generated files during compilation.
=> Batch: Added note about Windows Def Real-time protection

media-autobuild_suite.bat
Tested working for compilation and update script. Information taken from <https://ss64.com/nt/endlocal.html>.
Will help with trying to run without mintty.
=> Batch: Enclose sections off so that variables don't leak to each other.

media-autobuild_suite.bat
Seemed that _bitness was unnecessary since it was not referenced by anything else.
=> Batch: Condensed bitness and msys2arch

media-autobuild_suite.bat
Since msys2Arch can really only be one of two values.
=> Batch: Condensed msys2Arch

build/media-suite_compile.sh, build/media-suite_helper.sh, media-autobuild_suite.bat
Closes #970 and closes #977 
Added in noMintty
Changed how mintty/powershell(bash) is called
Changed how compilation_fail works if noMintty is enabled
Added the generation of bash.ps1 if noMintty is enabled
Reset color if using noMintty
If I made any mistakes, please tell me. I'm sick rn and probably will not be able to find them.
=> Batch & Helper & Compile: Added option for not using mintty. 

build/media-suite_compile.sh
I tested and the tags and the sha's are the same for 2.12.6.
=> Compile: Use frontconfig's new gitlab link

build/media-suite_helper.sh
Before (wrong):
`C:/PROGRA~1/NVIDIA~2/CUDA/v8.0/bin`
After (right):
`/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0`
=> CUDA bin path added to $PATH must be in UNIX format

build/media-suite_compile.sh
I don't know what their problem is right now but even pacman installing opencv won't make the error go away. Don't know either why it went through before without installing gavl but anyway: the more the better according to this:
https://www.dyne.org/software/frei0r/
=> frei0r: fix building

build/media-suite_compile.sh
They started [discussion](https://gitlab.com/gnutls/gnutls/merge_requests/905) again and someone requested to bring code coverage up-to-date now instead of working around it. So the previous patch cannot be applied to the 3.x stable tree, and master doesn't work yet for us here either because we are running on the latest autoconf. So using this branch is currently the only way to build gnutls successfully. We can switch later back to stable or master as you wish. I've been using master for several months now without any problems BTW, just saying. :+1:
=> gnutls: use tarball instead of git

build/media-suite_helper.sh
Adds a switch to not use binary mode for patches that download from places that add a cr to the lf (pastebin).
=> Helper: Add a switch to do_patch for plaintext

build/media-suite_compile.sh
Both 32 and 64 bit paths compile despite patching fails in both.
=> mplayer: fixpollfd patch is now obsolete

build/media-suite_compile.sh
For a successful quick test (this will simply burn-in the current timestamp into the video with a Standard Windows font) one can run:
`ffmpeg -y -report:level=debug -i input.mp4 -vf drawtext=fontsize=24:fontcolor=yellow:x=(w-text_w)/2:y=(h-text_h)-16:fontfile='C\:\\Windows\\Fonts\\Verdana.ttf':text="TimeStamp\\:%{pts\\:hms}":box=1:boxcolor=red:boxborderw=8 -c:v h264 -c:a copy output.mp4`
=> fontconfig: update to 2.13.1

build/media-suite_compile.sh
Reason for all this: https://github.com/tesseract-ocr/tesseract/commit/1c7e00611b5a6b0e2d2094f0a1326ff3c3e1fd98
Do you see any libs apart from nettle not installed with the base or should it be OK like this?
=> tesseract: fix linking with ffmpeg

build/media-suite_compile.sh
I'm looking into msys2 for 32bit right now again and as I see only now that libarchive was installed if mpv is enabled/=2 . So we need to install it here as well as otherwise it would produce an error if someone didn't include mpv.
=> tesseract: pacman install libarchive

media-autobuild_suite.bat
This should make it so that even if running a 32-bit cmd within a 64-bit cmd, msys2 will be 64-bit.
=> Batch: Add a catch if running 32-bit cmd under 64-bit OS. closes #1141

build/media-suite_compile.sh
Will be needed after https://github.com/mpv-player/mpv/pull/6476 is merged.
=> mpv: add libplacebo

build/media-suite_compile.sh
The prebuilt libtiff installs libjpeg-turbo as a dependency.
Install it since we now build libtiff from source.
Closes #1151
=> libtiff: install jpeg

media-autobuild_suite.bat
When chaging the background color some remote clients fail with the "dark gray" background (they set it as "black" background). So change it to "light gray".
Read about color range here: http://smallvoid.com/article/winnt-command-prompt-color.html
You can check the difference in a CONSOLE using "color 70" and "color 80".
=> Fix the color background

build/media-suite_compile.sh
- Switch to using github/gitlab mirrors for most non-cdn supported repositories (xiph, etc)
- Unbind ripgrep since there is now 11.0.1
- Switch to github ffmpeg mirrors
- Switch to videolan's new gitlab based code.videolan.org links
- Formatting: Add quotes around repo links and patch links
- Use hourly gitlab mirrors for notabug repos, or.cz, and fraunhofer's
- Mainly because my win10 vm does not want to properly pull from notabug and because I want to pull reliance off of dedicated servers and into major cdns.
- doing regular git clone and do_vcs outside of script works but inside script says connection timed out with 0b transferred
I think that I might see if I can do automatic fallback for repos to <https://gitlab.com/media-autobuild_suite-dependencies> in do_vcs in case the original …
=> Repository links

build/media-suite_compile.sh, build/media-suite_helper.sh
Closes #1182 
To disable uploading logs to 0x0, add `touch "$LOCALBUILDDIR/no_logs"` to *_extra.sh
This disables uploading logs globally regardless of the package failing to compile.
(@wiiaboo should this be changed to upload if the local package has no modification?)
There is nothing to remove the flag so if log uploading is desired, remove the flag by hand.
=> zip_logs: Add no_logs flag to disable zipping and uploading logs

build/media-suite_compile.sh
multiple target patterns error seems to happen with noMintty.
Seems to be a variable issue, however, I can't seem to find
what is conflicting.
=> mujs: Use separated env for make. Fixes #1097

.gitignore, build/bash.ps1, media-autobuild_suite.bat
Separate bash.ps1 for easier maintainability plus reduce write cycle every time the batch file runs.
Remove reliance on build64 variable from bash.ps1
=> bash.ps1: Move to separate file and fix regression from "bat: don't pass build64"

build/bash.ps1, build/media-suite_compile.sh, build/media-suite_helper.sh
Might hopefully fix not valid identifier errors when a compile fails with noMintty
=> noMintty: change how script fails and reads vars

build/media-suite_compile.sh
Closes #1162 
Since I don't know if it will ever be merged.
Prevents cmake from finding msys2's libm before mingw's
=> Don't use libm with libtiff due to conflict with libmsvcrt

build/media-suite_helper.sh
https://help.github.com/en/articles/linking-to-releases
Since I found out we can link to the latest release.
Although this won't work for repos that hardcodes the version in the filename
=> vswhere: use latests

build/media-suite_compile.sh
Do we need to worry about a 64bit version of upx?
I'm not entirely sure about this logic down below. It should be
``` bash
if [[ $build64 = y ]]; then
do_wget -h 5c076f87ba64d82f11513f4af0ceb07246a3540aa3c72ca3ffc2d53971fa56e3 \
"https://github.com/upx/upx/releases/download/v3.95/upx-3.95-win64.zip"
else
do_wget -h f94ff30b175d125d1c238458716f5808aee222547a813918b44d0f67035c0054 \
"https://github.com/upx/upx/releases/download/v3.95/upx-3.95-win32.zip"
fi
```
(haven't used brackets before really.)
=> upx: update to 3.95

.github/ISSUE_TEMPLATE, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/generic_bug_report.md, .github/ISSUE_TEMPLATE/request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/fix.md, .github/PULL_REQUEST_TEMPLATE/new.md, .github/PULL_REQUEST_TEMPLATE/update.md
Idk about the pr templates since I can't create a pr from a branch on a fork to the master of a fork, but the issue templates seem to work. The PR templates require the files to be in the master branch of the master repo. I can split the commits into individual templates for easy reverting in wanted.
Motivated by the recent lack of issue description in the title and lack of information of 32|64 bit builds etc.
e.g. "Compilation failed", "x265", "libwebp", etc
=> Github: Use markdown issue templates

build/media-suite_compile.sh
Line 920 had an extra `fi` that didn't allowed the media-suite from running.
Fixes #1240
=> Removed a "fi" that prevented the suite from running

build/media-suite_compile.sh, media-autobuild_suite.bat
I tried this outside of the suite, and it worked with these flags, however I would like someone else to test if it will compile properly, preferable with an older cpu. Reason why is that it sets -march=native in the cmake list and although it can be patched out, it does not change that compiling requires some extensions not present in x86_64. It seems it requires at least sse4.1 (gcc's nehalem, Intel first gen core or gcc's bdver1, AMD Bulldozer(I haven't tested on an AMD cpu yet because all of my AMD cpus are in use in linux boxes))
I does not seem that the BUILD_SHARED_LIBS=off actually do anything atm as it is hard coded .so right now. There is a pr to make it so that it can be turned off.
If I can confirm that this works, I can work on #1103 to integrate with x265.
=> Compile: Add SVT-HEVC

build/media-suite_helper.sh
Allows for extra_script to add flags for cmake
Allows for option to skip `create_build_dir` or pass a name to `create_build_dir`
=> do_cmake: add more variables and switches

build/media-suite_compile.sh
This PR attempts to fix the SVT-HEVC DLL library not being moved to the `bin-video` folder. 
I removed the `Svt-Hevc` folder since the do_cmakeinstall always placed the `SvtHevcEncApp.exe` in the `bin-video` folder. After the `do_cmakeinstall` I'm doing a `do_install` to copy the `libSvtHevcEnc.dll` DLL to the `bin-video` folder so that the suite is successful at running. Otherwise, it will fail and we have to press `Enter` to continue building.
=> SVT-HEVC: DLL not installed (moved) correctly

build/media-suite_helper.sh
Closes #1256
It seems that one of the flags is still being consumed, presumable due to the fact that the flags will be shifted regardless if $1 has been consumed or not
=> do_cmake: Dont bind $1 to bindir, fix non-local variable

build/media-suite_helper.sh
Test tput directly.
Is there anything else that requires the ncolors variable?
=> Helper: Remove unecessary ncolors variable

build/bash.ps1, build/media-suite_compile.sh, build/media-suite_helper.sh
Using Start-Process caused the cursor to reset to top left
Use declare -p since that doesn't output functions
=> NoMintty: Change how compile.sh fails

build/media-suite_compile.sh
Python3 is now the default python in msys2 and don't have the '3' suffix.
=> Fix rst2man/rst2html not being found

build/media-suite_update.sh
To be considered before #1305, split off from #1303
Would the confirmation for missing packages really be necessary? Logically speaking, since we have marked those packages as necessary for building certain tools and codecs, wouldn't they be considered a necessary/installed later on either way?
I have also included to use shfmt this time, (caused the case spread and indention, removal of quotes from the tests, and double equal for the tests) I can remove it if it seems unnecessary
=> Update: Shellcheck plus rework check packages

build/media-suite_helper.sh
experienced the same thing as https://github.com/jb-alvarado/media-autobuild_suite/issues/1339
found out that there was an extra `""` appended to the `FFMPEG_DEFAULT_OPTS`
=> do_getFFmpegConfig: strip no length options

media-autobuild_suite.bat
Closes #1343 
Get the scripts before running any msys2 stuff and also use powershell instead of using wget from msys2, moving reliance off of msys2 packages and onto windows
=> bat: Move getting scripts for build folder up

build/media-suite_compile.sh
Closes #1345
``` bash
time do_vcs https://github.com/google/angle.git angle-github
...
real    0m44.089s
user    0m12.337s
sys     0m13.566s
On another computer
┌ angle-github git  .................................. [Recently updated]
real    1m5.574s
user    0m12.402s
sys     0m6.068s
```
``` bash
time do_vcs https://chromium.googlesource.com/angle/angle angle-google
...
real    0m34.467s
user    0m14.244s
sys     0m14.144s
On another computer
┌ angle-google git  .................................. [Recently updated]
real    0m36.132s
user    0m14.120s
sys     0m6.098s
```
_Originally posted by @1480c1 in https://github.com/m-ab-s/media-autobuild_suite/issues/1345#issuecomment-521672890_
Seems to be faster(?)
=> Angle: Use googlesource link

build/media-suite_compile.sh
This PR will apply this Gist patch: https://gist.githubusercontent.com/moisesmcardona/96c58aaa6d5b83ca654f92d29733b5af/raw/860e96c0036e477aa573f27aeb94d3bfacc695da/copy-EbTime.h-to-install-directory.patch
It adds a line to SVT-HEVC CMakeLists.txt to copy `EbTime.h` to the install directory, making the current ffmpeg SVT-HEVC patch work and successfully builds ffmpeg.
Solves issue #1352
=> SVT-HEVC: replace ffmpeg patch with the patch from their repo.

media-autobuild_suite.bat
Adds `libsvtav1` to `ffmpeg_options_full` to add support for the SVT-AV1 encoder in ffmpeg.
Even if it seems to be broken right now, at least for me...
=> Add libsvtav1 to ffmpeg options full

media-autobuild_suite.bat
See https://github.com/msys2/MSYS2-packages/commit/a7d37497ba6bffeafe075ffdec8b0588b2493d62 and  https://github.com/msys2/MINGW-packages/issues/5803
> Prior to the change in mingw-w64 it had no effect so there is no loss by removing it.
=> Disable _FORTIFY_SOURCE

build/media-suite_helper.sh
check hash of the file (if present) before attempting to download a copy, this can save some time in some circumstances.
=> do_wget: check hash before download

build/media-suite_compile.sh
It seems that this is no longer a valid option.
Relevant commit: https://github.com/msys2/MINGW-packages/commit/b502c1c4e9866ef71e6e2e43c91c9af503b4563e
Upstream commit: https://github.com/webmproject/libwebp/commit/f4dd92565e1d31a5dba40976a6084ddd025d3ca6
=> webp: remove enable-experimental

build/media-suite_compile.sh
`CONFIG_LOWBITDEPTH` has been replaced by `FORCE_HIGHBITDEPTH_DECODING`
https://aomedia.googlesource.com/aom/+/refs/heads/master/build/cmake/aom_configure.cmake#28
=> aom: replace removed option

build/media-suite_helper.sh, media-autobuild_suite.bat
Add functions helpful for getting signatures for gpg and checking if a file is correct using a sig or asc file.
I might be able to add a check if the file starts properly, but that is already handled by gpg erroring out with non-zero
Split off from https://github.com/m-ab-s/media-autobuild_suite/pull/1221
=> Helper: Add get_signature, check_signature, and do_jq 

build/media-suite_compile.sh
Disabling avx512 was a temporary workaround for https://github.com/m-ab-s/media-autobuild_suite/issues/887
It doesn't break compilation anymore, so It could be reverted I guess.
=> vpx: re-enable avx512

build/media-suite_helper.sh
It sometimes tries to run lib/gcc instead of bin/gcc when ran by 3rd party programs (Meson, gobject-introspection)
=> create_ab_ccache: Use cygpath to fix instances of ccache failing execv

media-autobuild_suite.bat
Closes #1460
Should we only check for lib.exe or cl.exe? Is there some better way to detect running inside an MSVC environment?
=> bat: Add error if in MSVC environment

build/media-suite_compile.sh
I don't think the symbols conflict was ever reported upstream
=> Codec2: svn->git

build/media-suite_compile.sh
codec2 git source compiles but does not produce the c2sim.exe executable, making it fail at this step. This PR removes the check and also removes the pkgconfig since we are compiling the master branch now.
=> codec2: Remove check for c2sim.exe

build/media-suite_compile.sh
Fixes #1466
vmaf already has a meson build system so I'll just update the patch as they change their system. In the future, I might change it to a gist, but if it's a branch, if someone else wants to pick it up, they can fork it.
=> vmaf: Use out-of-source cmake instead of meson

media-autobuild_suite.bat
Using dynamically defined variables as commands doesn't really work right without using call. Conditional execution is much more reliable.
You would think that starting the line with `7z >nul 2>&1 && ` on line 1359 would be unnecessary, but nope, conditional execution with piped commands is (usually) reliant on the first command in the chain not being piped. (There's more to it than that but it's not worth getting into.)
Also updated the instructions on what to do if the extraction fails, since it gives the impression you're supposed to put the msys2 folder in the build folder.
=> Resolve msys2-base extraction errors

media-autobuild_suite.bat
I noticed the file stuck around so I figured the best time to clean it up is after the second rebase. It definitely shouldn't be needed anymore after that.
=> msys2-base.tar.xz cleanup once it's working

build/media-suite_compile.sh, build/media-suite_helper.sh
libtiff sometimes tried to compile jbig without jbig support available.
cmake is fine with CC="ccache gcc" etc for makefiles and ninja generators. It requires the wrapper when running with any others afaik
=> CMake: Don't use compile wrapper except for x265 g++

build/media-suite_compile.sh
Fixes https://github.com/m-ab-s/media-autobuild_suite/issues/1479 maybe
It seems most of the patches applied by msys2 is mainly just to fix warnings with the exception of the one that adds pathtools stuff.
=> libxml2: Compile our own

media-autobuild_suite.bat
Does the logic here seem correct?
Also, would it make sense to adhere to `msys2ArchINI`? I feel that it might be better to have it as script runtime dependant rather than using a predefined value since it could be that someone migrates the suite from 32-bit to 64-bit or visa versa.
=> bat: Rework INI logic

media-autobuild_suite.bat
Ignores a preset option that is usually generated the first time the ini file is written to.
Prevents potential issues of transferring the suite to another computer with the second computer's arch being different.
Only issue I can see with this is someone needing to redownload msys2 and packages going from a 32-bit system to a 64-bit one.
=> bat: Ignore ini value for msys2Arch

build/media-suite_helper.sh
@wiiaboo, do you think this would be a good idea? I feel that knowing the contents of `$PATH` and especially the ordering during a compilation can be helpful when trying to diagnose an issue, but I'm not sure if this could be considered too much since that's mainly outside of variables set/directly used by the suite.
=> create_diagnostic: Add path to diagnostic.txt

build/media-suite_compile.sh
@wiiaboo, is there a particular reason why we don't use cinstall directly to LOCALBUILDDIR with `--bindir`?
=> rav1e: Use jobs argument for cinstall

media-autobuild_suite.bat
The `bash.ps1` file was removed in the commit da663b5926e9562aa159b169a404df71bc32232e, but the script was still attempting to download this file.
Fixes #1541
=> Removed bash.ps1 from being downloaded since the file has been removed.

build/media-suite_compile.sh
This is a workaround for #1483 while Rust takes their time fixing the underlying issue.
=> Hack: Make __chkstk_ms from rav1e weak

build/media-suite_compile.sh, build/media-suite_helper.sh, media-autobuild_suite.bat
Closes #1547
it's a pain.
Adds a really long amount of time because of qt5 compilation, ccache is enabled so recompiles might not be so bad
Can't really use msys2's qt5-static since it's broken (not necessarily msys2's fault, it's mainly qt's fault due to a lot of reasons) and huge because it includes a lot of stuff we don't need and has a debug library version for each regular one. Generally followed what vlc has in their contrib/qt* folders.
Generally feels hack-ish because of qt5.
Right now compiling from a clean suite
=> VLC: add vlc

README.md, media-autobuild_suite.bat
Since we already have libdav1d for decoding av1, it would be good to also have a library to encode av1.
@wiiaboo any comments?
=> libaom: Move libaom to light build from zeranoe

build/media-suite_compile.sh, media-autobuild_suite.bat
tbh, the fact that none of them are mainline and contained parts for each other and thus makes the patches non-atomic is a pain.
@wiiaboo do you think there's any better way to order it?
@nistvan86 can you try using this branch?
=> ffmpeg: Add svt-vp9 encoder

build/media-suite_compile.sh
Added the following 2 patches:
* [vlc-corrected-patch](https://gist.github.com/moisespr123/2369978dc603ed1e67bdf7aba7304416): This is a rebase of the original patch by @1480c1 to make it apply to VLC's master branch.
* [medialib-patch](https://gist.github.com/moisespr123/70e16f70f5d016c3d0f0dacbf97526f0): This allows us to compile VLC using medialibrary master branch.
Note that VLC is still buggy. It will work, but will present an exception upon launching it. Press ignore and it will work. It has issues playing back videos (some doesn't open the video window. Other have distorted colors), but I'm sure this is not related to the above patches and is something else with the codecs.
Fixes #1583
=> VLC patches to allow compilation with the medialibrary master branch

media-autobuild_suite.bat
Since https://github.com/msys2/msys2-installer/releases doesn't have any i686 sfx.exe releases, I think this should be fine to merge. This just removes the ability to run the compile suite on 32-bit host machine, this does not affect mingw-w64-i686-* packages, so for now 32-bit can be compiled, but not compiled on.
=> bat: Drop support for 32-bit hosts

README.md
I noticed #1619 forgot to mention this in the documentation, so here it is.
=> Mention libsvtvp9 in README.md

build/media-suite_compile.sh
As far as I can tell, this is no longer necessary. Built and tested it, it works just fine.
=> Allow --enable-librav1e

README.md, build/media-suite_compile.sh, media-autobuild_suite.bat
Description
vulkan can be used by both ffmpeg and mpv, so move up its compilation to above ffmpeg.
(Optional)
Might fix #1565
=> ffmpeg: support libglslang and vulkan

build/media-suite_compile.sh
https://github.com/m-ab-s/media-autobuild_suite/pull/1619#issuecomment-616206347 taught me that ffmpeg cannot be compiled with SVT-VP9 while the SVT-AV1 and XVid options are enabled (and I did test to make sure XVid did indeed conflict). There doesn't seem to be anything to reference or handle this conflict other than these few comments, so I made a quick codeblock to do so.
I also revised the SVT-AV1 codeblock in the process. Much cleaner code seems a bit more important than trying to keep the log message down to a single line.
=> Add SVT-VP9 temporary workaround

README.md, build/media-suite_compile.sh, build/media-suite_helper.sh, build/media-suite_update.sh, doc/getting-started.md, media-autobuild_suite.bat
Wanted to get someone else to also look at this code before I merge it just to make sure.
ideally, `do_vcs` will
```bash
if ! proper repo; then
clone repo
fi
fetch updates, but not merge
get the merge-base of the current local repo and upstream
if not checked recently; then
reset to upstream
fi
check if merge base != current hash and return new updates
rest of the logic stuff
```
for mplayer, I just put a static version of `do_vcs` with the unnecessary stuff removed, so as long as svn doesn't change or anything, it shouldn't need to be changed. I am considering just maybe moving the actual code into a subshell inside the if, but that also seems like it would cause a lot of ugliness.
maybe another time I might actually look a bit more at cleaning up the mplayer portion
=> do_vcs: drop mercurial and svn

build/media-suite_compile.sh
GitLab reminded: Project 'media-autobuild_suite-dependencies/VVCSoftware_VTM' was moved to 'm-ab-s/VVCSoftware_VTM'.
=> Update VVC git URL to m-ab-s

build/media-suite_compile.sh, build/media-suite_helper.sh
@1480c1 I don't have write-access to mabs-patches
Also, since you're probably more familiar than me with CMake, am I doing something wrong with the MASM detection part?
Do you know any reason why we shouldn't do this?
=> vulkan-loader: rebase and add support for uasm as masm-like assembler

build/media-suite_compile.sh
The commit hashes for the git repo at Bitbucket are broken, resulting in the x265 cli and lib reporting "HEVC encoder version unknown" since https://github.com/videolan/x265/commit/4191822.
Fixed by switching to the VideoLAN repo.
=> Switch to VideoLAN mirror of x265

build/media-suite_compile.sh
Fix `../meson.build:1:0: ERROR: Unknown options: "fontconfig"`
=> harfbuzz: remove obsolete option "fontconfig"

media-autobuild_suite.bat
Fix `You have more packages than needed!` and `You're missing some packages!` messages about `autoconf` package
[update.stripped.log](https://github.com/m-ab-s/media-autobuild_suite/files/7911883/update.stripped.log)
=> bat: install autoconf-wrapper instead of autoconf

media-autobuild_suite.bat
- misleading  VVC software name (Fraunhofer VVC), which is not used in the build script
- build script is using the VVC Reference Software VTM (https://gitlab.com/m-ab-s/VVCSoftware_VTM.git) 
- if Fraunhofer VVC software should be used, VVenC/VVdeC have to be added as a build step
=> using correct name for VVC software

build/media-suite_compile.sh
The patch (and subsequent libjxl.pc file edit) are no longer needed, as [both](https://github.com/libjxl/libjxl/commit/9c1e1c1446982bddf6987a6236f0731e826570ad) [fixes](https://github.com/libjxl/libjxl/commit/1c1d40ce76dfad7f4dd4861bd598cef2aafa48a9) are now in upstream
Doxygen is disabled for libjxl because other libraries in the suite similarly disable Doxygen support, and I was also getting some errors when trying to build libjxl with it enabled
=> libjxl: remove non-applying patch, disable doxygen

README.md, build/media-suite_compile.sh, media-autobuild_suite.bat
See issue: #1810 
Added vvenc & vvdec, but not tested yet, others vvc programs are coming soon...
Update of 16th June 2022: vvenc & vvdec is only now support of media autobuild suite, others were not.
- Martin Eesmaa
=> Add additional VVC program suits into autobuild media

build/media-suite_compile.sh, media-autobuild_suite.bat
This patch allows to specify a path to a custom ffmpeg repo in the `media_autobuild_suite.ini` file:
It can be a URL or a local path.
=> Allow specifying a custom ffmpeg source repo

build/media-suite_compile.sh, media-autobuild_suite.bat
The build process can take several hours. In case of build errors, one is usually tempted to fix the error and re-run the build, but continuing on failed state with changes does not exactly guarantee the same result (or even a successful result) as when re-builing from scratch with those changes applied.
Having exit points like added by this commit allows to perform a build incrementally and cleanly from point-to-point, when the intermediate results are saved each time.
This is also very useful for setting up automated builds via GH actions or DevOps where intermediate results are cached only when no errors have occurred.
=> Early Exit: Provide a way to cleanly exit the build at defined points

build/media-suite_compile.sh
Fixes https://github.com/m-ab-s/media-autobuild_suite/issues/2427
This was changed in upstream in the commit
https://github.com/libjxl/libjxl/commit/f8c76c0adebff3c23acb28b782105e6538010750
=> libjxl: Replace cjpeg_hdr with cjpegli

build/media-suite_compile.sh
Vorbis depends on ogg, so it must be downloaded and installed first.
Fixes #2491
=> Ogg to be installed before vorbis

build/media-suite_compile.sh, build/media-suite_deps.sh
A couple of small fixes to help get the suite back on track.  It basically just pins mpv to the 0.36 release tag, since they removed waf completely after that, thus making newer revs unable to be compiled by the suite for now.  I noted that a prior PR was submitted to update mpv's build procedures, so this should help band-aid mpv until you get that worked out.
The shaderc portion removes the cloning of the dependencies into third-party and just runs the git-sync-deps script included with shaderc.  This should pull the known-good commits for each dependency (as listed in the DEPS file), which not only follows their build docs, but also should cut down on the frequency that shaderc compilation breaks because they haven't accounted for upstream dependency changes yet.
Somewhat unrelated to …
=> Small fixes to shaderc and mpv (with info on luajit)

build/media-suite_compile.sh
This change forces dovi_tool to build/install only the static lib rather than both static and dynamic libs.  Should prevent libplacebo (and thus ffmpeg) from dynamically linking to and depending on dovi.dll.
=> dovi_tool: Just build static libdovi

build/media-suite_compile.sh
The vidstab filters in FFmpeg master now support reading and writing both ASCII and binary data
=> Remove vidstab patch

build/media-suite_compile.sh
The Ogg library is required to compile Vorbis.
Ogg is only compiled when standalone binaries were requested.
Vorbis compilation fails as ogg is missing when standalone librairies are not resqested
=> remove the standalone condition for compiling ogg
Corrections #2580
=> fix: #2580 remove standalone condition for ogg compilation

build/media-suite_compile.sh, build/media-suite_helper.sh
* Update upx (version 3.96 is over 4 years old)
* Only build libtiff tools if standalone is set
* Change vcs_clone to perform treeless clones to save space and time
=> Minor changes

build/media-suite_compile.sh, build/media-suite_deps.sh
Rust is installed via msys2's package now, so install cargo-c as a package too. /opt/cargo/bin is deleted on every update, so this prevents repetitive recompilation. 
Fixes #2667
=> cargo-c: install msys2 package instead of compiling from source

media-autobuild_suite.bat
harfbuzz has been made a dep for the drawtext filter but isn't passed as an arg to ffmpeg configure, so the filter isn't present in builds
=> Add harfbuzz to zeranoe options

build/media-suite_compile.sh
SVT-AV1 encoder can be used in 64-bit build of avifenc
Fixes https://github.com/m-ab-s/media-autobuild_suite/issues/2692
=> Add SVT-AV1 codec to libavif

build/media-suite_compile.sh
They are supported in FFmpeg.
Also I think they should both enabled in configure options to make ffmpeg actually have the ability to demux dvd?
=> dvdread&dvdnav: check enabled for ffmpeg

build/media-suite_compile.sh
The decoder was completely removed from SVT-AV1
=> SVT-AV1: remove check for decoder

build/media-suite_compile.sh
Enables AVX-512 optimizations for CPUs that support it, which can speed up encoding by a few percent
=> SVT-AV1: Added AVX-512 compile flag

build/media-suite_compile.sh, build/media-suite_helper.sh
=> FLAC autoconf to cmake migration and some minor change

build/media-suite_compile.sh
In a benchmark against the current multithreaded vapoursynth demuxer included in ffmpeg 7 and vspipe as external provider, the alternative demuxer was the slowest by far. Efforts to fix the patch being linkable again seem to have low priority, if any at all.
Fixes #2766
=> Remove alternative vapoursynth demuxer from ffmpeg

build/media-suite_compile.sh
It is superfluous now, x265 builds without.
=> Remove x265 library path/file split patch

build/media-suite_compile.sh
Patch failed, built anyway. So it is probably implemented now.
=> vulkan-loader: remove windows-Static-linking-hacks.patch

build/media-suite_compile.sh, build/media-suite_helper.sh, media-autobuild_suite.bat
Since the suite installs rust via msys2 instead of rustup, [this commit](https://github.com/m-ab-s/media-autobuild_suite/commit/87ece8ec16088504a341f812706aba944f13dcd8) is no longer necessary since [the issue it works around](https://github.com/m-ab-s/media-autobuild_suite/issues/2207#issuecomment-1152897236) isn't encountered on msys2's rust. All rust libraries build fine after this change, and also appear to run fine (tested Av1an, rav1e, and dssim).
This also means Clang is no longer a strict requirement for building on MINGW32/64, so ~1GB can be saved when the suite is installed for the first time. Clang now only installs when building Av1an or ffmpeg with cuda-llvm enabled, since they both require libclang to compile.
=> Minimize Clang usage in MINGW envs

build/media-suite_helper.sh
Although cuda-llvm is included in default ffmpeg options, when using custom ffmpeg options, if the cuda-llvm is not explicitly disabled (it should be implicitly disabled by --disable-autodetect which is default option too) it will move on to install the clang package.
If a user, now, after the removal of clang from default packages, and is using GCC toolchain, "implicitly disabled" cuda-llvm by remove or comment out the line in ffmpeg_options, the clang package will be installed without any actual use.
I'm not entirely sure what this part of the code is intended for, maybe this is not the best way to prevent it.
=> prevent superfluous clang installation during FFmpeg compilation

build/media-suite_compile.sh, build/media-suite_helper.sh, media-autobuild_suite.bat
Reduce the number of packages installed when the suite is first run, which saves about 350MB (2.40GB -> 2.05GB on MINGW64)
Since the msys version of python is no longer installed with this change, the mingw version is specified whenever python is called. Tested on MINGW64 and everything compiled fine
=> suite: download less packages on first install

README.md, build/media-suite_compile.sh, build/media-suite_deps.sh, doc/forcing-recompilations.md, media-autobuild_suite.bat
Adds gifski, a high quality gif encoder in Rust. I've also included the option to build gifski with built-in video support via ffmpeg 6.1, because it's apparently [very difficult](https://github.com/ImageOptim/gifski/?tab=readme-ov-file#with-built-in-video-support) to set up (none of the Windows releases have video support).
=> suite: add gifski

build/media-suite_compile.sh
djpegli.exe is not stripped off unnecessary symbols if it is not included in the checks set
=> JPEG-XL: Check for djpegli.exe too

README.md, build/media-suite_compile.sh, build/media-suite_deps.sh, doc/forcing-recompilations.md, media-autobuild_suite.bat
Adds the option to compile zlib along with a selection of forks compatible with zlib's API (zlib-chromium, zlib-cloudflare, and zlib-ng).
I didn't take the approach of installing zlib-ng as an msys2 package [like I had suggested a few months ago](https://github.com/m-ab-s/media-autobuild_suite/issues/2812#issue-2760276465) because I didn't feel like waiting for it to be added much longer. I also tried adding zlib-rs too, but after building (what I think was) a valid zlib-API compatible library I got this error trying to link it with ffmpeg (I may try adding zlib-rs at a later date, so this is just here for my own reference):
```
ccache gcc -D_ISOC11_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DWIN32_LEAN_AND_MEAN -U__STRICT_ANSI__ -D__USE_MINGW_ANSI_STDIO=1 …
```
=> suite: add option to compile zlib

build/media-suite_compile.sh, build/media-suite_helper.sh
(Possibly temporary?) fix for https://github.com/m-ab-s/media-autobuild_suite/issues/2870
=> Minimum CMake version 3.5 into media-suite_helper.sh:do_cmake() and media-suite_compile.sh:do_x265_cmake()

build/media-suite_compile.sh, build/media-suite_helper.sh
* Clean rust build folders with `cargo clean -q` in `clean_suite()`. This provides the most impactful results with Av1an, where nearly 1GB of space can be saved by cleaning the build folder.
* Create `do_git_submodule()` to replace half a dozen manual `git submodule` calls. `--jobs "$cpuCount"` pulls submodules in parallel, and `--filter=tree:0` pulls each submodule as a treeless clone, which speeds up submodule cloning and reduces the size of submodules (in testing, libjxl's submodules cloned several seconds faster and the build folder went from 573MB to 351MB).
* Remove an obsolete sed call for building curl. The file `Makefile.in` doesn't exist when it is called, and after running the command when Makefile.in would exist (after `do_autoreconf`), it does nothing and the file remains …
=> Some changes & a fix

build/media-suite_compile.sh, media-autobuild_suite.bat
Tested compilation without `-liconv` in `LDFLAGS`, and it appears only fontconfig has an issue with the library not being linked. Since fontconfig needs iconv during link time whether or not the feature is enabled, I decided to just add `-Diconv=enabled` so iconv would automatically link and get added to the .pc file.
=> suite: revert adding -liconv to link flags, enable iconv in fontconfig

build/media-suite_compile.sh
Build with GCC 15 fails due to missing header
=> Include missing stdint header in x265

build/media-suite_compile.sh
heif-view.exe was added in https://github.com/strukturag/libheif/commit/e20d44e7c10607965f1d754746ae8993bd1e3534
=> Add heif-view.exe to _check

build/media-suite_compile.sh
The jpegli source has been branched from libjxl - according to the libjxl CMakeLists.txt, the default is libjpeg-turbo from the third_party subrepo (which is pulled by mabs).
I've used -DJPEGXL_ENABLE_JPEGLI=OFF in a libjxl_extra.sh for quite some time, but always had to remove the tools check for cjpegli/djpegli from media-suite_compile.sh
Moving jpegli completely outside libjxl and using a dependency seems to have stalled, but nevertheless jpegli development doesn't happen inside libjxl anymore. If the jpegli tools should be a built-in feature of mabs (probably not), it should be separate and use https://github.com/google/jpegli
If mabs should require a jpeg lib in local, it should be separate from the legacy 'just happens to be there' jpegli inside libjxl, too.
=> Disable (legacy) jpegli inside libjxl

build/media-suite_compile.sh
Correct a typo in media_suite_compile.sh.
=> Fix typo (CFLGAS -> CFLAGS)

build/media-suite_compile.sh, build/media-suite_deps.sh, media-autobuild_suite.bat
Sed code is based of  [M05QU170](https://github.com/user-attachments/files/19558379/media-suite_compile-audiotoolbox.patch) patch.
I'm not really sure if this is the right way to do this....
Also current implementation might not [decode probably](https://github.com/AnimMouse/QTFiles/tree/v12.10.11?tab=readme-ov-file#icudt62dll-dummy-file), though my limited testing show no difference between the original `icudt62.dll` and the dummy one.
=> Add support for AudioToolbox via AudioToolboxWrapper

build/media-suite_compile.sh
Fixes https://github.com/m-ab-s/media-autobuild_suite/issues/2926 and partially addresses https://github.com/m-ab-s/media-autobuild_suite/issues/2922 and https://github.com/m-ab-s/media-autobuild_suite/issues/2927 (only the undefined LIBCLANG_PATH error, not the missing advapi32 symbols error)
=> Fix gifski, zlib-chromium (clang), and partially fix av1an

build/media-suite_helper.sh
This allows *_extra.sh scripts to also print out something to the console, it also adds an option so no Running ... message gets displayed for the scripts.
=> Allow *_extra.sh scripts to print info.

build/media-suite_compile.sh
glslang no longer builds libSPVRemapper as a separate object as of https://github.com/KhronosGroup/glslang/commit/e70645c4571fb5136f2fb3f27f25daff2b83cfa6.
=> Remove obsolete artifact in glslang check.

build/media-suite_deps.sh
It seems the default branch of `libpng` has been changed to `libpng18`. While it is preferable to use the new version, this PR will stick with the previous version to minimize impact.
=> libpng: Checkout explicitly `libpng16` branch
